gText_ObtainedTheItem::
	.string "Hai ricevuto {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "La BORSA è piena…$"

gText_PutItemInPocket::
	.string "Meglio metterlo nella\n"
	.string "borsa.$"

gText_PlayerFoundOneItem::
	.string "Gas ha trovato {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "La BORSA è piena…$"

gText_PlayerPutItemInBag::
	.string "Gas mette {STR_VAR_2}\n"
	.string "nella BORSA.$"

gText_ObtainedTheDecor::
	.string "Hai ottenuto {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Non hai spazio per un altro\n"
	.string "{STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"
