	.align 2
gText_ConfirmSave::
	.string "Cos'è ci hai la scaga Gassi Gas?$"

gText_AlreadySavedFile::
	.string "C'è già un salvataggio.\n"
	.string "Lo vuoi sovrascrivere?$"

gText_SavingDontTurnOff::
	.string "SALVATAGGIO…\n"
	.string "DON'T TURN OFF THE POWER BOY.$"

gText_PlayerSavedGame::
	.string "Gas ha salvato il gioco.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "POKéMON, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "SALVATAGGIO…\n"
	.string "DON'T TURN OFF THE POWER BOY.$"
