SantaGiustina_MapScripts::
	.byte 0


SantaGiustina_EventScript_PortaChiusa::
	msgbox SantaGiustina_EventScript_PortaChiusa_Text_0
	closemessage
	return


SantaGiustina_EventScript_CartelloTown::
	msgbox SantaGiustina_EventScript_CartelloTown_Text_0
	closemessage
	return


SantaGiustina_EventScript_Striscione1::
	msgbox SantaGiustina_EventScript_Striscione1_Text_0
	closemessage
	return


SantaGiustina_EventScript_Striscione2::
	msgbox SantaGiustina_EventScript_Striscione1_Text_0
	closemessage
	return


SantaGiustina_EventScript_Striscione3::
	msgbox SantaGiustina_EventScript_Striscione1_Text_0
	closemessage
	return


SantaGiustina_EventScript_Striscione4::
	msgbox SantaGiustina_EventScript_Striscione1_Text_0
	closemessage
	return


SantaGiustina_EventScript_Striscione5::
	msgbox SantaGiustina_EventScript_Striscione1_Text_0
	closemessage
	return


SantaGiustina_EventScript_Striscione6::
	msgbox SantaGiustina_EventScript_Striscione1_Text_0
	closemessage
	return


SantaGiustina_EventScript_CentroMon::
	msgbox SantaGiustina_EventScript_CentroMon_Text_0
	closemessage
	return


SantaGiustina_EventScript_CartelloSquadra::
	msgbox SantaGiustina_EventScript_CartelloSquadra_Text_0
	closemessage
	return


SantaGiustina_EventScript_PortaChiusa_Text_0:
	.string "La porta è chiusa, come è normale che\n"
	.string "sia.$"

SantaGiustina_EventScript_CartelloTown_Text_0:
	.string "SANTA GIUSTINA$"

SantaGiustina_EventScript_Striscione1_Text_0:
	.string "Ho il cancro.$"

SantaGiustina_EventScript_CentroMon_Text_0:
	.string "Centro Pokémon. Curiamo i tuoi\n"
	.string "Pokemons.$"

SantaGiustina_EventScript_CartelloSquadra_Text_0:
	.string "Casa di Squadra$"
