.set LOCALID_COLE, 2
.set LOCALID_GERALD, 3
.set LOCALID_AXLE, 4
.set LOCALID_DANIELLE, 5

SantaGiustina_Gym_1F_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, SantaGiustina_Gym_1F_OnTransition
	.byte 0

SantaGiustina_Gym_1F_OnTransition:
	call SantaGiustina_Gym_1F_EventScript_SetTrainerTempVars
	call SantaGiustina_Gym_1F_EventScript_CheckBuryTrainers
	end

@ Unclear where/if these temp vars are getting checked
SantaGiustina_Gym_1F_EventScript_SetTrainerTempVars::
	setvar VAR_TEMP_B, 0
	setvar VAR_TEMP_C, 0
	setvar VAR_TEMP_D, 0
	setvar VAR_TEMP_E, 0
	setvar VAR_TEMP_F, 0
	goto_if_defeated TRAINER_COLE, SantaGiustina_Gym_1F_EventScript_SetGeraldTempVar
	setvar VAR_TEMP_B, 1
SantaGiustina_Gym_1F_EventScript_SetGeraldTempVar::
	goto_if_defeated TRAINER_GERALD, SantaGiustina_Gym_1F_EventScript_SetAxleTempVar
	setvar VAR_TEMP_C, 1
SantaGiustina_Gym_1F_EventScript_SetAxleTempVar::
	goto_if_defeated TRAINER_AXLE, SantaGiustina_Gym_1F_EventScript_SetDanielleTempVar
	setvar VAR_TEMP_D, 1
SantaGiustina_Gym_1F_EventScript_SetDanielleTempVar::
	goto_if_defeated TRAINER_DANIELLE, SantaGiustina_Gym_1F_EventScript_EndSetTrainerTempVars
	setvar VAR_TEMP_E, 1
SantaGiustina_Gym_1F_EventScript_EndSetTrainerTempVars::
	return

SantaGiustina_Gym_1F_EventScript_CheckBuryTrainers::
	goto_if_defeated TRAINER_COLE, SantaGiustina_Gym_1F_EventScript_CheckBuryGerald
	setobjectmovementtype LOCALID_COLE, MOVEMENT_TYPE_BURIED
SantaGiustina_Gym_1F_EventScript_CheckBuryGerald::
	goto_if_defeated TRAINER_GERALD, SantaGiustina_Gym_1F_EventScript_CheckBuryAxle
	setobjectmovementtype LOCALID_GERALD, MOVEMENT_TYPE_BURIED
SantaGiustina_Gym_1F_EventScript_CheckBuryAxle::
	goto_if_defeated TRAINER_AXLE, SantaGiustina_Gym_1F_EventScript_CheckBuryDanielle
	setobjectmovementtype LOCALID_AXLE, MOVEMENT_TYPE_BURIED
SantaGiustina_Gym_1F_EventScript_CheckBuryDanielle::
	goto_if_defeated TRAINER_DANIELLE, SantaGiustina_Gym_1F_EventScript_EndCheckBuryTrainers
	setobjectmovementtype LOCALID_DANIELLE, MOVEMENT_TYPE_BURIED
SantaGiustina_Gym_1F_EventScript_EndCheckBuryTrainers::
	return

SantaGiustina_Gym_1F_EventScript_Flannery::
	trainerbattle_single TRAINER_FLANNERY_1, SantaGiustina_Gym_1F_Text_FlanneryIntro, SantaGiustina_Gym_1F_Text_FlanneryDefeat, SantaGiustina_Gym_1F_EventScript_FlanneryDefeated, NO_MUSIC
	specialvar VAR_RESULT, ShouldTryRematchBattle
	goto_if_eq VAR_RESULT, TRUE, SantaGiustina_Gym_1F_EventScript_FlanneryRematch
	goto_if_unset FLAG_RECEIVED_TM50, SantaGiustina_Gym_1F_EventScript_GiveOverheat2
	msgbox SantaGiustina_Gym_1F_Text_FlanneryPostBattle, MSGBOX_DEFAULT
	release
	end

SantaGiustina_Gym_1F_EventScript_FlanneryDefeated::
	message SantaGiustina_Gym_1F_Text_ReceivedHeatBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	msgbox SantaGiustina_Gym_1F_Text_ExplainHeatBadgeTakeThis, MSGBOX_DEFAULT
	setflag FLAG_WHITEOUT_TO_SANTA
	setflag FLAG_DEFEATED_SANTA_GYM
	setflag FLAG_BADGE04_GET
	addvar VAR_PETALBURG_GYM_STATE, 1
	call_if_eq VAR_PETALBURG_GYM_STATE, 6, Common_EventScript_ReadyPetalburgGymForBattle
	setvar VAR_0x8008, 4
	call Common_EventScript_SetGymTrainers
	setflag FLAG_HIDE_RIMINI_MARE_WANDAS_HOUSE_WALLY
	setvar VAR_SANTA_GIUSTINA_STATE, 1
	call SantaGiustina_Gym_1F_EventScript_GiveOverheat
	closemessage
	delay 30
	playfanfare MUS_REGISTER_MATCH_CALL
	msgbox SantaGiustina_Gym_1F_Text_RegisteredFlannery, MSGBOX_DEFAULT
	waitfanfare
	closemessage
	delay 30
	setflag FLAG_ENABLE_FLANNERY_MATCH_CALL
	release
	end

SantaGiustina_Gym_1F_EventScript_GiveOverheat2::
	giveitem ITEM_TM50
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	msgbox SantaGiustina_Gym_1F_Text_ExplainOverheat, MSGBOX_DEFAULT
	setflag FLAG_RECEIVED_TM50
	release
	end

SantaGiustina_Gym_1F_EventScript_GiveOverheat::
	giveitem ITEM_TM50
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_BagIsFull
	msgbox SantaGiustina_Gym_1F_Text_ExplainOverheat, MSGBOX_DEFAULT
	setflag FLAG_RECEIVED_TM50
	return

SantaGiustina_Gym_1F_EventScript_FlanneryRematch::
	trainerbattle_rematch_double TRAINER_FLANNERY_1, SantaGiustina_Gym_1F_Text_FlanneryPreRematch, SantaGiustina_Gym_1F_Text_FlanneryRematchDefeat, SantaGiustina_Gym_1F_Text_FlanneryRematchNeedTwoMons
	msgbox SantaGiustina_Gym_1F_Text_FlanneryPostRematch, MSGBOX_AUTOCLOSE
	end

SantaGiustina_Gym_1F_EventScript_Cole::
	trainerbattle TRAINER_BATTLE_CONTINUE_SCRIPT, TRAINER_COLE, LOCALID_COLE, SantaGiustina_Gym_1F_Text_ColeIntro, SantaGiustina_Gym_1F_Text_ColeDefeat, SantaGiustina_Gym_EventScript_CheckTrainerScript
	msgbox SantaGiustina_Gym_1F_Text_ColePostBattle, MSGBOX_AUTOCLOSE
	end

SantaGiustina_Gym_EventScript_CheckTrainerScript::
	call SantaGiustina_Gym_1F_EventScript_SetTrainerTempVars
	release
	special ShouldTryGetTrainerScript
	goto_if_eq VAR_RESULT, 1, EventScript_GotoTrainerScript
	end

SantaGiustina_Gym_1F_EventScript_Axle::
	trainerbattle TRAINER_BATTLE_CONTINUE_SCRIPT, TRAINER_AXLE, LOCALID_AXLE, SantaGiustina_Gym_1F_Text_AxleIntro, SantaGiustina_Gym_1F_Text_AxleDefeat, SantaGiustina_Gym_EventScript_CheckTrainerScript
	msgbox SantaGiustina_Gym_1F_Text_AxlePostBattle, MSGBOX_AUTOCLOSE
	end

SantaGiustina_Gym_B1F_EventScript_Keegan::
	trainerbattle TRAINER_BATTLE_CONTINUE_SCRIPT, TRAINER_KEEGAN, LOCALID_KEEGAN, SantaGiustina_Gym_B1F_Text_KeeganIntro, SantaGiustina_Gym_B1F_Text_KeeganDefeat, SantaGiustina_Gym_EventScript_CheckTrainerScript
	msgbox SantaGiustina_Gym_B1F_Text_KeeganPostBattle, MSGBOX_AUTOCLOSE
	end

SantaGiustina_Gym_1F_EventScript_Danielle::
	trainerbattle TRAINER_BATTLE_CONTINUE_SCRIPT, TRAINER_DANIELLE, LOCALID_DANIELLE, SantaGiustina_Gym_1F_Text_DanielleIntro, SantaGiustina_Gym_1F_Text_DanielleDefeat, SantaGiustina_Gym_EventScript_CheckTrainerScript
	msgbox SantaGiustina_Gym_1F_Text_DaniellePostBattle, MSGBOX_AUTOCLOSE
	end

SantaGiustina_Gym_1F_EventScript_Gerald::
	trainerbattle TRAINER_BATTLE_CONTINUE_SCRIPT, TRAINER_GERALD, LOCALID_GERALD, SantaGiustina_Gym_1F_Text_GeraldIntro, SantaGiustina_Gym_1F_Text_GeraldDefeat, SantaGiustina_Gym_EventScript_CheckTrainerScript
	msgbox SantaGiustina_Gym_1F_Text_GeraldPostBattle, MSGBOX_AUTOCLOSE
	end

SantaGiustina_Gym_B1F_EventScript_Jace::
	trainerbattle TRAINER_BATTLE_CONTINUE_SCRIPT, TRAINER_JACE, LOCALID_JACE, SantaGiustina_Gym_B1F_Text_JaceIntro, SantaGiustina_Gym_B1F_Text_JaceDefeat, SantaGiustina_Gym_EventScript_CheckTrainerScript
	msgbox SantaGiustina_Gym_B1F_Text_JacePostBattle, MSGBOX_AUTOCLOSE
	end

SantaGiustina_Gym_B1F_EventScript_Jeff::
	trainerbattle TRAINER_BATTLE_CONTINUE_SCRIPT, TRAINER_JEFF, LOCALID_JEFF, SantaGiustina_Gym_B1F_Text_JeffIntro, SantaGiustina_Gym_B1F_Text_JeffDefeat, SantaGiustina_Gym_EventScript_CheckTrainerScript
	msgbox SantaGiustina_Gym_B1F_Text_JeffPostBattle, MSGBOX_AUTOCLOSE
	end

SantaGiustina_Gym_B1F_EventScript_Eli::
	trainerbattle TRAINER_BATTLE_CONTINUE_SCRIPT, TRAINER_ELI, LOCALID_ELI, SantaGiustina_Gym_B1F_Text_EliIntro, SantaGiustina_Gym_B1F_Text_EliDefeat, SantaGiustina_Gym_EventScript_CheckTrainerScript
	msgbox SantaGiustina_Gym_B1F_Text_EliPostBattle, MSGBOX_AUTOCLOSE
	end

SantaGiustina_Gym_1F_EventScript_GymGuide::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_SANTA_GYM, SantaGiustina_Gym_1F_EventScript_GymGuidePostVictory
	msgbox SantaGiustina_Gym_1F_Text_GymGuideAdvice, MSGBOX_DEFAULT
	release
	end

SantaGiustina_Gym_1F_EventScript_GymGuidePostVictory::
	msgbox SantaGiustina_Gym_1F_Text_GymGuidePostVictory, MSGBOX_DEFAULT
	release
	end

SantaGiustina_Gym_1F_EventScript_LeftGymStatue::
	lockall
	goto_if_set FLAG_BADGE04_GET, SantaGiustina_Gym_1F_EventScript_GymStatueCertified
	goto SantaGiustina_Gym_1F_EventScript_GymStatue
	end

SantaGiustina_Gym_1F_EventScript_RightGymStatue::
	lockall
	goto_if_set FLAG_BADGE04_GET, SantaGiustina_Gym_1F_EventScript_GymStatueCertified
	goto SantaGiustina_Gym_1F_EventScript_GymStatue
	end

SantaGiustina_Gym_1F_EventScript_GymStatueCertified::
	msgbox SantaGiustina_Gym_1F_Text_GymStatueCertified, MSGBOX_DEFAULT
	releaseall
	end

SantaGiustina_Gym_1F_EventScript_GymStatue::
	msgbox SantaGiustina_Gym_1F_Text_GymStatue, MSGBOX_DEFAULT
	releaseall
	end

SantaGiustina_Gym_1F_Text_GymGuideAdvice:
	.string "Hey, how's it going, CHAMPION-\n"
	.string "bound {PLAYER}?\p"
	.string "SANTA's GYM LEADER FLANNERY\n"
	.string "uses FIRE-type POKéMON.\p"
	.string "Her passion for POKéMON burns stronger\n"
	.string "and hotter than a volcano.\p"
	.string "Don't get too close to her--you'll burn!\n"
	.string "Hose her down with water and then\l"
	.string "go for it!$"

SantaGiustina_Gym_1F_Text_GymGuidePostVictory:
	.string "Yow! That was a scorching-hot battle!$"

SantaGiustina_Gym_1F_Text_ColeIntro:
	.string "Owowowowow!\n"
	.string "Yikes, it's hot!$"

SantaGiustina_Gym_1F_Text_ColeDefeat:
	.string "I'm blinded by sweat in my eyes…$"

SantaGiustina_Gym_1F_Text_ColePostBattle:
	.string "Being buried in hot sand promotes\n"
	.string "circulation.\p"
	.string "It's effective for healing pain in\n"
	.string "your joints.$"

SantaGiustina_Gym_1F_Text_AxleIntro:
	.string "I'm trying to relieve my stress.\n"
	.string "Don't come along and stress me out!$"

SantaGiustina_Gym_1F_Text_AxleDefeat:
	.string "I hope FLANNERY flames you good!$"

SantaGiustina_Gym_1F_Text_AxlePostBattle:
	.string "Haaah… Whew…\p"
	.string "If you spend too much time buried in\n"
	.string "hot sand, it tuckers you out…$"

SantaGiustina_Gym_B1F_Text_KeeganIntro:
	.string "You must be getting tired by now.\n"
	.string "You'd like to rest in the hot sand,\l"
	.string "wouldn't you?\p"
	.string "But you should know that maintaining\n"
	.string "your willpower is an important ability\l"
	.string "for all TRAINERS.$"

SantaGiustina_Gym_B1F_Text_KeeganDefeat:
	.string "Play with fire, and be burned…$"

SantaGiustina_Gym_B1F_Text_KeeganPostBattle:
	.string "Your skill is real…\n"
	.string "But our LEADER FLANNERY is strong.\p"
	.string "If you don't watch yourself, you'll be\n"
	.string "burned seriously.$"

SantaGiustina_Gym_1F_Text_GeraldIntro:
	.string "Can your POKéMON withstand\n"
	.string "392-degree heat?$"

SantaGiustina_Gym_1F_Text_GeraldDefeat:
	.string "It didn't burn hotly enough…$"

SantaGiustina_Gym_1F_Text_GeraldPostBattle:
	.string "The temperature of magma is\n"
	.string "392 degrees.\p"
	.string "Your POKéMON beat me, so they should\n"
	.string "easily survive in magma.$"

SantaGiustina_Gym_1F_Text_DanielleIntro:
	.string "Um…\n"
	.string "Okay, I'll battle with you.$"

SantaGiustina_Gym_1F_Text_DanielleDefeat:
	.string "Oh, but you're too strong.$"

SantaGiustina_Gym_1F_Text_DaniellePostBattle:
	.string "I'm going to be a pretty and strong\n"
	.string "TRAINER just like FLANNERY.$"

SantaGiustina_Gym_B1F_Text_JaceIntro:
	.string "Come on, get with it!\n"
	.string "Let's go before my feelings cool!$"

SantaGiustina_Gym_B1F_Text_JaceDefeat:
	.string "It's so hot, and yet my heart is\n"
	.string "clutched by ice…$"

SantaGiustina_Gym_B1F_Text_JacePostBattle:
	.string "The way the battling spirit burns\n"
	.string "within you, you may stand a chance\l"
	.string "against our LEADER.$"

SantaGiustina_Gym_B1F_Text_JeffIntro:
	.string "See how the flames blaze wildly?\n"
	.string "They flare in anticipation of my win!$"

SantaGiustina_Gym_B1F_Text_JeffDefeat:
	.string "Something didn't go right.$"

SantaGiustina_Gym_B1F_Text_JeffPostBattle:
	.string "Well, so what? I say so what?\n"
	.string "I can walk on hot coals barefoot!\p"
	.string "…Don't even think about trying it!$"

SantaGiustina_Gym_B1F_Text_EliIntro:
	.string "As much as I love mountains,\n"
	.string "I especially love volcanoes.$"

SantaGiustina_Gym_B1F_Text_EliDefeat:
	.string "Well, it seems to me I lost without\n"
	.string "ever being in control.$"

SantaGiustina_Gym_B1F_Text_EliPostBattle:
	.string "I stay here because I became a fan\n"
	.string "of FLANNERY's power.\p"
	.string "Hehehehe.$"

SantaGiustina_Gym_1F_Text_FlanneryIntro:
	.string "Welcome… No, wait.\p"
	.string "Puny TRAINER, how good to see you've\n"
	.string "made it here!\p"
	.string "I have been entrusted with the…\n"
	.string "No, wait.\p"
	.string "I am FLANNERY, and I'm the GYM\n"
	.string "LEADER here!\p"
	.string "Uh…\n"
	.string "Dare not underestimate me, though\l"
	.string "I have been LEADER only a short time!\p"
	.string "With skills inherited from my grand-\n"
	.string "father, I shall, uh…demonstrate the\l"
	.string "hot moves we have honed on this land!$"

SantaGiustina_Gym_1F_Text_FlanneryDefeat:
	.string "Oh…\n"
	.string "I guess I was trying too hard…\p"
	.string "I… I've only recently become\n"
	.string "a GYM LEADER.\p"
	.string "I tried too hard to be someone\n"
	.string "I'm not.\p"
	.string "I have to do things my natural way. If\n"
	.string "I don't, my POKéMON will be confused.\p"
	.string "Thanks for teaching me that.\n"
	.string "For that, you deserve this.$"

SantaGiustina_Gym_1F_Text_ReceivedHeatBadge:
	.string "{PLAYER} received the HEAT BADGE\n"
	.string "from FLANNERY.$"

SantaGiustina_Gym_1F_Text_ExplainHeatBadgeTakeThis:
	.string "If you have a HEAT BADGE, all POKéMON\n"
	.string "up to Level 50, even those you get in\l"
	.string "trades from other people, will obey\l"
	.string "you completely.\p"
	.string "And, it lets POKéMON use the HM move\n"
	.string "STRENGTH outside of battle.\p"
	.string "This is a token of my appreciation.\n"
	.string "Don't be shy about taking it!$"

SantaGiustina_Gym_1F_Text_ExplainOverheat:
	.string "That TM50 contains OVERHEAT.\p"
	.string "That move inflicts serious damage on\n"
	.string "the opponent.\p"
	.string "But it also sharply cuts the SP. ATK\n"
	.string "of the POKéMON using it. It might not\l"
	.string "be suitable for longer battles.$"

SantaGiustina_Gym_1F_Text_RegisteredFlannery:
	.string "Registered GYM LEADER FLANNERY\n"
	.string "in the POKéNAV.$"

SantaGiustina_Gym_1F_Text_FlanneryPostBattle:
	.string "Your power reminds me of someone…\p"
	.string "Oh! I know! You battle like NORMAN,\n"
	.string "the GYM LEADER of PETALBURG.$"

SantaGiustina_Gym_1F_Text_GymStatue:
	.string "SANTA TOWN POKéMON GYM$"

SantaGiustina_Gym_1F_Text_GymStatueCertified:
	.string "SANTA TOWN POKéMON GYM\p"
	.string "FLANNERY'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

SantaGiustina_Gym_1F_Text_FlanneryPreRematch:
	.string "FLANNERY: Losing a battle isn't going\n"
	.string "to deflate me.\p"
	.string "I love POKéMON.\n"
	.string "I love to battle.\l"
	.string "And… I love this GYM!\p"
	.string "Let's exchange superhot moves\n"
	.string "in another battle!$"

SantaGiustina_Gym_1F_Text_FlanneryRematchDefeat:
	.string "Whew!\n"
	.string "On the verge of eruption!$"

SantaGiustina_Gym_1F_Text_FlanneryPostRematch:
	.string "FLANNERY: I lost the match,\n"
	.string "but I'm completely satisfied.\p"
	.string "It's not often I get to enjoy a battle\n"
	.string "this heated.\p"
	.string "Let's have another one like this\n"
	.string "again sometime!$"

SantaGiustina_Gym_1F_Text_FlanneryRematchNeedTwoMons:
	.string "FLANNERY: Losing a battle isn't going\n"
	.string "to deflate me.\p"
	.string "I love POKéMON.\n"
	.string "I love to battle.\l"
	.string "And… I love this GYM!\p"
	.string "Let's exchange superhot moves\n"
	.string "in another battle!\p"
	.string "Oh, wait. Do you only have one POKéMON\n"
	.string "that can battle?\p"
	.string "I hate to say this, but when you come\n"
	.string "see me, bring at least two POKéMON.$"
