RiminiTown_Mare_MapScripts::
	.byte 0


RiminiTown_Mare_EventScript_VecchioSinistra::
	lockall
	msgbox RiminiTown_Mare_EventScript_VecchioSinistra_Text_0
	closemessage
	releaseall
	return


RiminiTown_Mare_EventScript_Gabbiano::
	lockall
	msgbox RiminiTown_Mare_EventScript_Gabbiano_Text_0
	closemessage
	releaseall
	return


RiminiTown_Mare_EventScript_OminoVerde::
	lockall
	msgbox RiminiTown_Mare_EventScript_OminoVerde_Text_0
	closemessage
	releaseall
	return


RiminiTown_Mare_EventScript_TipaInAcqua::
	lockall
	msgbox RiminiTown_Mare_EventScript_TipaInAcqua_Text_0
	closemessage
	releaseall
	return


RiminiTown_Mare_EventScript_CartelloCasaChecco::
	lockall
	msgbox RiminiTown_Mare_EventScript_CartelloCasaChecco_Text_0
	closemessage
	releaseall
	return


RiminiTown_Mare_EventScript_SkateShop::
	lockall
	msgbox RiminiTown_Mare_EventScript_SkateShop_Text_0
	closemessage
	releaseall
	return


RiminiTown_Mare_EventScript_VecchioSinistra_Text_0:
	.string "Mej un óv incù che una galena dman!$"

RiminiTown_Mare_EventScript_Gabbiano_Text_0:
	.string "I gabbiani sono la rovina del mare...$"

RiminiTown_Mare_EventScript_OminoVerde_Text_0:
	.string "Mi dicono ci sia un nuovo skate shop a\n"
	.string "Marina Centro. Se non fosse gay andare\l"
	.string "con lo skate andrei a visitarlo...$"

RiminiTown_Mare_EventScript_TipaInAcqua_Text_0:
	.string "L'acqua bella tiepida oggi, si vede che\n"
	.string "hanno aperto le fogne...$"

RiminiTown_Mare_EventScript_CartelloCasaChecco_Text_0:
	.string "Casa di Checco$"

RiminiTown_Mare_EventScript_SkateShop_Text_0:
	.string "Negozio di Skateboards$"
